name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: | 
        dotnet tool restore
        dotnet restore
        ls .paket
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Publish
      uses: rohan-buchner/publish-gh-package@v1.1.4
      with:
        # Filepath of the project to be packaged, relative to root of repository
        PROJECT_FILE_PATH: src/fs-http-client-mock/fs-http-client-mock.fsproj
        # NuGet package id, used for version detection & defaults to project name
        PACKAGE_NAME: # optional
        # Filepath with version info, relative to root of repository & defaults to PROJECT_FILE_PATH
        VERSION_FILE_PATH: # optional
        # Regex pattern to extract version info in a capturing group
        VERSION_REGEX: # optional, default is ^\s*<Version>(.*)<\/Version>\s*$
        # Useful with external providers like Nerdbank.GitVersioning, ignores VERSION_FILE_PATH & VERSION_REGEX
        VERSION_STATIC: # optional
        # Flag to toggle git tagging, enabled by default
        TAG_COMMIT: false
        # Format of the git tag, [*] gets replaced with actual version
        TAG_FORMAT: # optional, default is v*
        # API key to authenticate with NuGet server
        NUGET_KEY: # optional
        # NuGet server uri hosting the packages, defaults to https://nuget.pkg.github.com
        NUGET_SOURCE: # optional, default is https://nuget.pkg.github.com
        # The Organisation Name
        ORGANISATION: # default is Organisation
        # Flag to toggle pushing symbols along with nuget package to the server, disabled by default
        INCLUDE_SYMBOLS: true