name: .NET

on:
  push:
    branches: 
      - 'release/*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0 # avoid shallow clone so nbgv can do its work. 
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: | 
        dotnet tool restore
        dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: publish
      env: 
        NUGET_KEY : ${{ secrets.NUGET_KEY }}
      run: |
        version=$(dotnet nbgv get-version -v Version)
        dotnet pack -p:PackageVersion=$version --no-build --include-symbols -o build/ src/fs-http-client-mock/fs-http-client-mock.fsproj
        dotnet nuget push -s https://api.nuget.org/v3/index.json -k $NUGET_KEY build/FsHttpClientMock.${version}.nupkg
